/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedCompararRouteImport } from './routes/_authenticated/comparar'
import { Route as AuthenticatedEconomiaRouteImport } from './routes/_authenticated/economia'
import { Route as AuthenticatedListaRouteImport } from './routes/_authenticated/lista'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompararRoute = AuthenticatedCompararRouteImport.update({
  id: '/comparar',
  path: '/comparar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEconomiaRoute = AuthenticatedEconomiaRouteImport.update({
  id: '/economia',
  path: '/economia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedListaRoute = AuthenticatedListaRouteImport.update({
  id: '/lista',
  path: '/lista',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app': typeof AuthenticatedAppRoute
  '/comparar': typeof AuthenticatedCompararRoute
  '/economia': typeof AuthenticatedEconomiaRoute
  '/lista': typeof AuthenticatedListaRoute
  '/perfil': typeof AuthenticatedPerfilRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app': typeof AuthenticatedAppRoute
  '/comparar': typeof AuthenticatedCompararRoute
  '/economia': typeof AuthenticatedEconomiaRoute
  '/lista': typeof AuthenticatedListaRoute
  '/perfil': typeof AuthenticatedPerfilRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/comparar': typeof AuthenticatedCompararRoute
  '/_authenticated/economia': typeof AuthenticatedEconomiaRoute
  '/_authenticated/lista': typeof AuthenticatedListaRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/app'
    | '/comparar'
    | '/economia'
    | '/lista'
    | '/perfil'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/app'
    | '/comparar'
    | '/economia'
    | '/lista'
    | '/perfil'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/app'
    | '/_authenticated/comparar'
    | '/_authenticated/economia'
    | '/_authenticated/lista'
    | '/_authenticated/perfil'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comparar': {
      id: '/_authenticated/comparar'
      path: '/comparar'
      fullPath: '/comparar'
      preLoaderRoute: typeof AuthenticatedCompararRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/economia': {
      id: '/_authenticated/economia'
      path: '/economia'
      fullPath: '/economia'
      preLoaderRoute: typeof AuthenticatedEconomiaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lista': {
      id: '/_authenticated/lista'
      path: '/lista'
      fullPath: '/lista'
      preLoaderRoute: typeof AuthenticatedListaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedCompararRoute: typeof AuthenticatedCompararRoute
  AuthenticatedEconomiaRoute: typeof AuthenticatedEconomiaRoute
  AuthenticatedListaRoute: typeof AuthenticatedListaRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedCompararRoute: AuthenticatedCompararRoute,
  AuthenticatedEconomiaRoute: AuthenticatedEconomiaRoute,
  AuthenticatedListaRoute: AuthenticatedListaRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
